---
# Options
simp_options::dns::servers: ['8.8.8.8']
simp_options::ntpd::servers: ['time.nist.gov']
simp_options::ldap::bind_pw: 's00per sekr3t!'
simp_options::ldap::bind_hash: '{SSHA}foobarbaz!!!!'
simp_options::ldap::sync_pw: 's00per sekr3t!'
simp_options::ldap::sync_hash: '{SSHA}foobarbaz!!!!'
simp_options::ldap::root_hash: '{SSHA}foobarbaz!!!!'
simp_options::auditd: true
simp_options::fips: false
simp_options::haveged: true
simp_options::logrotate: true
simp_options::pam: true
simp_options::selinux: true
simp_options::stunnel: true
simp_options::tcpwrappers: true
simp_options::firewall: true
simp_options::package_ensure: installed
sssd::domains: ['LOCAL']

# Settings required for acceptance test, some may be required
simp::scenario: simp
simp_options::clamav: false
simp_options::pki: true
simp_options::pki::source: '/etc/pki/simp-testing/pki'
simp_options::trusted_nets: ['0.0.0.0/0']
simp::yum::os_update_url: http://mirror.centos.org/centos/$releasever/os/$basearch/
simp::yum::enable_simp_repos: false
simp::scenario::base::puppet_server_hosts_entry: false

pupmod::master::log_level: INFO
# Make sure puppet doesn't run (hopefully)
pupmod::agent::cron::minute: '0'
pupmod::agent::cron::hour: '0'
pupmod::agent::cron::weekday: '0'
pupmod::agent::cron::month: '1'

# Settings to make beaker happy
sudo::user_specifications:
  vagrant_all:
    user_list: ['vagrant']
    cmnd: ['ALL']
    passwd: false
pam::access::users:
  defaults:
    origins:
      - ALL
    permission: '+'
  vagrant:
ssh::server::conf::permitrootlogin: true
ssh::server::conf::authorizedkeysfile: .ssh/authorized_keys
