---
.cache_bundler: &cache_bundler
  cache:
    untracked: true
    # A broad attempt at caching between runs (ala Travis CI)
    key: "${CI_PROJECT_NAMESPACE}__bundler"
    paths:
      - '.vendor'
      - 'vendor'

.setup_bundler_env: &setup_bundler_env
  before_script:
    - 'echo Files in cache: $(find .vendor | wc -l) || :'
    - 'export GEM_HOME=.vendor/gem_install'
    - 'export BUNDLE_CACHE_PATH=.vendor/bundler'
    - 'declare GEM_BUNDLER_VER=(-v ''~> ${BUNDLER_VERSION:-1.16.0}'')'
    - declare GEM_INSTALL=(gem install --no-document)
    - declare BUNDLER_INSTALL=(bundle install --no-binstubs --jobs $(nproc) --path=.vendor "${FLAGS[@]}")
    - gem list -ie "${GEM_BUNDLE_VER[@]}" --silent bundler || "${GEM_INSTALL[@]}" --local "${GEM_BUNDLE_VER[@]}" bundler || "${GEM_INSTALL[@]}" "${GEM_BUNDLE_VER[@]}" bundler
    - 'rm -rf pkg/ || :'
    - bundle check || rm -f Gemfile.lock && ("${BUNDLER_INSTALL[@]}" --local || "${BUNDLER_INSTALL[@]}")

stages:
  - integration



default_el6:
  stage: integration
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10.7'
  script:
    - bundle exec rake beaker:suites[default,el6_server]
  retry: 1

default_el7:
  stage: integration
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10.7'
  script:
    - bundle exec rake beaker:suites[default,el7_server]
  retry: 1

rpm_el6:
  stage: integration
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10.7'
  script:
    - bundle exec rake beaker:suites[install_from_rpm,el6_server]
  retry: 1

rpm_el7:
  stage: integration
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10.7'
  script:
    - bundle exec rake beaker:suites[install_from_rpm,el7_server]
  retry: 1

forge_install_el6:
  stage: integration
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10.7'
  script:
    - bundle exec rake beaker:suites[install_from_core_module,el6_server]
  retry: 1

forge_install_el7:
  stage: integration
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10.7'
  script:
    - bundle exec rake beaker:suites[install_from_core_module,el7_server]
  retry: 1


# Just gonna comment this one out for now...
# acceptance-rpm_docker:
#   stage: acceptance
#   tags:
#     - beaker
#   <<: *cache_bundler
#   <<: *setup_bundler_env
#   script:
#     - rm Gemfile.lock || true
#     - bundle install --no-binstubs --path=vendor
#     - bundle exec rake beaker:suites[rpm_docker]
