---
HOSTS:
  el7-build-server:
    roles:
      - primary
    platform: el-7-x86_64
    hypervisor: docker
    dockerfile: spec/acceptance/suites/rpm_docker/nodesets/docker_el7/Dockerfile
    image: simp_core/build-el7
    docker_preserve_image: true

  el6-build-server:
    roles:
      - disabled
      - secondary
    platform: el-6-x86_64
    hypervisor: docker
    dockerfile: spec/acceptance/suites/rpm_docker/nodesets/docker_el7/Dockerfile
    image: simp_core/build-el6
    docker_preserve_image: true

CONFIG:
  mount_folders:
    simp_core:
      host_path: './'
      container_path: '/simp-core'
      opts: Z
  log_level: verbose
  type: aio
